/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iu.poker;

import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JPanel;

/**
 *
 * @author Romi
 */
public class PanelDatosJugador extends javax.swing.JPanel {

    private BufferedImage image;
    private ControladorPanelDatosJugador controlador;

    /**
     * Creates new form PanelDatosJugador
     */
    public PanelDatosJugador() {
        initComponents();
        try {
            image = ImageIO.read(new File("src/imgs/barrajugador.png"));
        } catch (IOException ex) {
            //Logger.getLogger(PanelDatosJugador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void setControlador(ControladorPanelDatosJugador controlador) {
        this.controlador = controlador;
        //this.controlador.addObserver(this);
        actualizar();
    }

    public void actualizar() {
        try {
            lblNombreJugador.setText(controlador.getDatosJugador().getNombre());
            lblSaldoJugador.setText("" + controlador.getSaldoJugador());
        } catch (Throwable ex) {
            //ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new Panel("src/imgs/panel.png");
        jLabel1 = new javax.swing.JLabel();
        lblNombreJugador = new javax.swing.JLabel();
        jPanel2 = new Panel("src/imgs/panel.png");
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblSaldoJugador = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(327, 36));
        setMinimumSize(new java.awt.Dimension(327, 36));
        setOpaque(false);

        jPanel1.setMaximumSize(new java.awt.Dimension(174, 36));
        jPanel1.setMinimumSize(new java.awt.Dimension(174, 36));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(174, 36));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Jugador:");
        jPanel1.add(jLabel1, new java.awt.GridBagConstraints());

        lblNombreJugador.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNombreJugador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreJugador.setText("nombreJugador");
        jPanel1.add(lblNombreJugador, new java.awt.GridBagConstraints());

        jPanel2.setMaximumSize(new java.awt.Dimension(174, 36));
        jPanel2.setMinimumSize(new java.awt.Dimension(174, 36));
        jPanel2.setOpaque(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(174, 36));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel3.setText("Saldo:");
        jPanel2.add(jLabel3, new java.awt.GridBagConstraints());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("$");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel2.add(jLabel4, gridBagConstraints);

        lblSaldoJugador.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblSaldoJugador.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSaldoJugador.setText("saldoJugador");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel2.add(lblSaldoJugador, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblNombreJugador;
    private javax.swing.JLabel lblSaldoJugador;
    // End of variables declaration//GEN-END:variables

    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        if (image != null) {
            g.drawImage(image, 0, 0, getWidth(), getHeight(), null);
        }
    }

    private class Panel extends JPanel {

        private BufferedImage image;

        protected Panel(String path) {
            try {
                image = ImageIO.read(new File(path));
            } catch (IOException ex) {
                Logger.getLogger(PanelAccionesJugador.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        @Override
        public void paintComponent(Graphics g) {
            super.paintComponent(g);
            if (image != null) {
                g.drawImage(image, 0, 0, getWidth(), getHeight(), null);
            }
        }
    }
}
